/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChatbot: typeof import('./src/components/AIChatbot.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CharacterComponent: typeof import('./src/components/CharacterInformationComponent.vue')['default']
    CharacterInformationComponent: typeof import('./src/components/CharacterInformationComponent.vue')['default']
    DictionarySearch: typeof import('./src/components/DictionarySearch.vue')['default']
    FooterNavigation: typeof import('./src/components/FooterNavigation.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PolitePastNegativeForm: typeof import('./src/components/PolitePastNegativeForm.vue')['default']
    Quizz1: typeof import('./src/components/quizzes/Quizz1.vue')['default']
    Quizz2: typeof import('./src/components/quizzes/Quizz2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarMenu: typeof import('./src/components/SidebarMenu.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
}
