/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/exercises/Flashcard': RouteRecordInfo<'/exercises/Flashcard', '/exercises/Flashcard', Record<never, never>, Record<never, never>>,
    '/exercises/Grammar': RouteRecordInfo<'/exercises/Grammar', '/exercises/Grammar', Record<never, never>, Record<never, never>>,
    '/exercises/Listening': RouteRecordInfo<'/exercises/Listening', '/exercises/Listening', Record<never, never>, Record<never, never>>,
    '/exercises/Reading': RouteRecordInfo<'/exercises/Reading', '/exercises/Reading', Record<never, never>, Record<never, never>>,
    '/exercises/Translation': RouteRecordInfo<'/exercises/Translation', '/exercises/Translation', Record<never, never>, Record<never, never>>,
    '/Homepage': RouteRecordInfo<'/Homepage', '/Homepage', Record<never, never>, Record<never, never>>,
    '/kanji/KanjiList': RouteRecordInfo<'/kanji/KanjiList', '/kanji/KanjiList', Record<never, never>, Record<never, never>>,
    '/LandingPage': RouteRecordInfo<'/LandingPage', '/LandingPage', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/CausativeConjugation': RouteRecordInfo<'/lessons/conjugation/CausativeConjugation', '/lessons/conjugation/CausativeConjugation', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/ConditionalConjugation': RouteRecordInfo<'/lessons/conjugation/ConditionalConjugation', '/lessons/conjugation/ConditionalConjugation', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/ConjugationIntroduction': RouteRecordInfo<'/lessons/conjugation/ConjugationIntroduction', '/lessons/conjugation/ConjugationIntroduction', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/Dictionary': RouteRecordInfo<'/lessons/conjugation/Dictionary', '/lessons/conjugation/Dictionary', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/ImperativeConjugation': RouteRecordInfo<'/lessons/conjugation/ImperativeConjugation', '/lessons/conjugation/ImperativeConjugation', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/PassiveConjugation': RouteRecordInfo<'/lessons/conjugation/PassiveConjugation', '/lessons/conjugation/PassiveConjugation', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/PoliteNegativeNonPast': RouteRecordInfo<'/lessons/conjugation/PoliteNegativeNonPast', '/lessons/conjugation/PoliteNegativeNonPast', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/PoliteNonPast': RouteRecordInfo<'/lessons/conjugation/PoliteNonPast', '/lessons/conjugation/PoliteNonPast', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/PolitePastForm': RouteRecordInfo<'/lessons/conjugation/PolitePastForm', '/lessons/conjugation/PolitePastForm', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/PolitePastNegativeForm': RouteRecordInfo<'/lessons/conjugation/PolitePastNegativeForm', '/lessons/conjugation/PolitePastNegativeForm', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/PotentialVerbConjugation': RouteRecordInfo<'/lessons/conjugation/PotentialVerbConjugation', '/lessons/conjugation/PotentialVerbConjugation', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/TeConjugationForm': RouteRecordInfo<'/lessons/conjugation/TeConjugationForm', '/lessons/conjugation/TeConjugationForm', Record<never, never>, Record<never, never>>,
    '/lessons/conjugation/VolitionalConjugation': RouteRecordInfo<'/lessons/conjugation/VolitionalConjugation', '/lessons/conjugation/VolitionalConjugation', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/Addition': RouteRecordInfo<'/lessons/conjunctions/Addition', '/lessons/conjunctions/Addition', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/CauseAndEffect': RouteRecordInfo<'/lessons/conjunctions/CauseAndEffect', '/lessons/conjunctions/CauseAndEffect', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/Condition': RouteRecordInfo<'/lessons/conjunctions/Condition', '/lessons/conjunctions/Condition', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/Constractive': RouteRecordInfo<'/lessons/conjunctions/Constractive', '/lessons/conjunctions/Constractive', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/Emphasis': RouteRecordInfo<'/lessons/conjunctions/Emphasis', '/lessons/conjunctions/Emphasis', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/Sequential': RouteRecordInfo<'/lessons/conjunctions/Sequential', '/lessons/conjunctions/Sequential', Record<never, never>, Record<never, never>>,
    '/lessons/conjunctions/Summarizing': RouteRecordInfo<'/lessons/conjunctions/Summarizing', '/lessons/conjunctions/Summarizing', Record<never, never>, Record<never, never>>,
    '/lessons/Introduction': RouteRecordInfo<'/lessons/Introduction', '/lessons/Introduction', Record<never, never>, Record<never, never>>,
    '/lessons/Lessons': RouteRecordInfo<'/lessons/Lessons', '/lessons/Lessons', Record<never, never>, Record<never, never>>,
    '/lessons/numbers/AgeExpression': RouteRecordInfo<'/lessons/numbers/AgeExpression', '/lessons/numbers/AgeExpression', Record<never, never>, Record<never, never>>,
    '/lessons/numbers/Introduction': RouteRecordInfo<'/lessons/numbers/Introduction', '/lessons/numbers/Introduction', Record<never, never>, Record<never, never>>,
    '/lessons/numbers/PhoneNumber': RouteRecordInfo<'/lessons/numbers/PhoneNumber', '/lessons/numbers/PhoneNumber', Record<never, never>, Record<never, never>>,
    '/lessons/numbers/TellingTime': RouteRecordInfo<'/lessons/numbers/TellingTime', '/lessons/numbers/TellingTime', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_De': RouteRecordInfo<'/lessons/particles/Particle_De', '/lessons/particles/Particle_De', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_E': RouteRecordInfo<'/lessons/particles/Particle_E', '/lessons/particles/Particle_E', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Ga': RouteRecordInfo<'/lessons/particles/Particle_Ga', '/lessons/particles/Particle_Ga', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Ha': RouteRecordInfo<'/lessons/particles/Particle_Ha', '/lessons/particles/Particle_Ha', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Kara': RouteRecordInfo<'/lessons/particles/Particle_Kara', '/lessons/particles/Particle_Kara', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Made': RouteRecordInfo<'/lessons/particles/Particle_Made', '/lessons/particles/Particle_Made', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Mo': RouteRecordInfo<'/lessons/particles/Particle_Mo', '/lessons/particles/Particle_Mo', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Ni': RouteRecordInfo<'/lessons/particles/Particle_Ni', '/lessons/particles/Particle_Ni', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_No': RouteRecordInfo<'/lessons/particles/Particle_No', '/lessons/particles/Particle_No', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_To': RouteRecordInfo<'/lessons/particles/Particle_To', '/lessons/particles/Particle_To', Record<never, never>, Record<never, never>>,
    '/lessons/particles/Particle_Wo': RouteRecordInfo<'/lessons/particles/Particle_Wo', '/lessons/particles/Particle_Wo', Record<never, never>, Record<never, never>>,
    '/lessons/questions/How': RouteRecordInfo<'/lessons/questions/How', '/lessons/questions/How', Record<never, never>, Record<never, never>>,
    '/lessons/questions/Introduction': RouteRecordInfo<'/lessons/questions/Introduction', '/lessons/questions/Introduction', Record<never, never>, Record<never, never>>,
    '/lessons/questions/What': RouteRecordInfo<'/lessons/questions/What', '/lessons/questions/What', Record<never, never>, Record<never, never>>,
    '/lessons/questions/When': RouteRecordInfo<'/lessons/questions/When', '/lessons/questions/When', Record<never, never>, Record<never, never>>,
    '/lessons/questions/Where': RouteRecordInfo<'/lessons/questions/Where', '/lessons/questions/Where', Record<never, never>, Record<never, never>>,
    '/lessons/questions/Who': RouteRecordInfo<'/lessons/questions/Who', '/lessons/questions/Who', Record<never, never>, Record<never, never>>,
    '/lessons/questions/Why': RouteRecordInfo<'/lessons/questions/Why', '/lessons/questions/Why', Record<never, never>, Record<never, never>>,
    '/lessons/vocabularies/Calendar': RouteRecordInfo<'/lessons/vocabularies/Calendar', '/lessons/vocabularies/Calendar', Record<never, never>, Record<never, never>>,
    '/lessons/vocabularies/Family': RouteRecordInfo<'/lessons/vocabularies/Family', '/lessons/vocabularies/Family', Record<never, never>, Record<never, never>>,
    '/lessons/vocabularies/Institutions': RouteRecordInfo<'/lessons/vocabularies/Institutions', '/lessons/vocabularies/Institutions', Record<never, never>, Record<never, never>>,
    '/lessons/vocabularies/Occupation': RouteRecordInfo<'/lessons/vocabularies/Occupation', '/lessons/vocabularies/Occupation', Record<never, never>, Record<never, never>>,
    '/lessons/writingsystem/Hiragana': RouteRecordInfo<'/lessons/writingsystem/Hiragana', '/lessons/writingsystem/Hiragana', Record<never, never>, Record<never, never>>,
    '/lessons/writingsystem/Kanji': RouteRecordInfo<'/lessons/writingsystem/Kanji', '/lessons/writingsystem/Kanji', Record<never, never>, Record<never, never>>,
    '/lessons/writingsystem/Katakana': RouteRecordInfo<'/lessons/writingsystem/Katakana', '/lessons/writingsystem/Katakana', Record<never, never>, Record<never, never>>,
    '/mocktest/MockTest': RouteRecordInfo<'/mocktest/MockTest', '/mocktest/MockTest', Record<never, never>, Record<never, never>>,
  }
}
